### ISSUE TITLE
Cannot compile on clang

### ISSUE THREAD

**Issue by Frityet** [brisklib/brisk#42]
```yaml
vscode ➜ /workspaces/brisktest $ /usr/bin/clang++ --version
Debian clang version 20.1.5 (++20250430014513+ebfae55af454-1~exp1~20250430014528.110)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-20/bin
```

`libc++` is installed and available too.

Error log: https://gist.github.com/Frityet/7dcbb4a14b0cd18e6f9e612121e3f2ad

Build invoked with `/usr/bin/cmake -DCMAKE_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/home/vscode/.xmake/packages/b/brisk/0.9.8/987f14589dcc428c9a712193ab8423ec -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_STATIC_LINKER_FLAGS_RELEASE= -DCMAKE_EXE_LINKER_FLAGS_RELEASE= "-DCMAKE_CXX_FLAGS_RELEASE= -O3 -DNDEBUG" -DCMAKE_SHARED_LINKER_FLAGS_RELEASE= "-DCMAKE_C_FLAGS_RELEASE= -O3 -DNDEBUG" /home/vscode/.xmake/cache/packages/2505/b/brisk/0.9.8/source/brisk
